name: End-to-end tests
on: [push]
jobs:
  test-suites:
    runs-on: ubuntu-latest
    # Stop the occasional rogue instance before the 6h GitHub limit
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install everything
        run: npm install
      - name: Ng test for studio-web
        run: |
          npx nx build web-component
          npx nx test:once studio-web
      - name: Cypress run for web-component
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: |
            npx nx serve web-component
            npx nx serve-test-data web-component
          wait-on: 'http://localhost:3333/build/web-component.esm.js'
          command: npx nx test:once web-component
      - name: Check that i18n and l10n are up to date
        run: |
          cd packages/studio-web
          npx nx extract-i18n studio-web
          if git status | grep i18n/messages; then echo The i18n database is out of date.; git diff; npm run check-fr-l10n || echo The fr l10n database is also out of date.; false; else echo The i18n database is up to date.; fi
          if npm run check-fr-l10n; then echo The fr l10n database is up to date.; else echo The fr l10n database is out of date.; false; fi
