name: Run Tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: |
          # We use --force because angular-shepherd 15 is not released yet and
          # 14 has dependencies that are incompatible with angular 15
          npm install --force
      - name: Test
        run: |
          npm run test:once
